# Generated by Django 5.0.7 on 2024-08-03 17:05

import django.core.validators
import funcionarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Nome completo deve conter apenas letras e espaços.', regex='^[a-zA-ZÀ-ÿ\\s]*$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('idade', models.PositiveIntegerField(validators=[funcionarios.models.Funcionario.validate_idade])),
                ('altura', models.FloatField(validators=[funcionarios.models.Funcionario.validate_altura])),
                ('peso', models.FloatField(validators=[funcionarios.models.Funcionario.validate_peso])),
            ],
        ),
    ]
